# ~/.config/starship.toml
# See:
#   https://starship.rs/config/

[hostname]
disabled = false
ssh_only = false
format = "[$ssh_symbol](bold blue) on [$hostname](bold red)"

[git_status]
disabled = false
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[localip]
disabled = false
ssh_only = false
format = "@[$localipv4](bold red) "
